{% set name = "structlog-gcp" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/structlog_gcp-{{ version }}.tar.gz
  sha256: 361da96886023e6fb8fa49f60f5278aff666820c8987534ca61e091b32047592

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - structlog

test:
  imports:
    - structlog_gcp
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A structlog set of processors to output as Google Cloud Logging format
  home: https://github.com/multani/structlog-gcp
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
