bot:
  automerge: true
  check_solvable: true
  inspection: update-all
  run_deps_from_wheel: true
conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
